### PR TITLE
Send kubernetes api and container level metrics to influx

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
I would like to install these in are 3 clusters. Starting with the Frankfurt one.
The problem here is that i have to customize 1 value per cluster in https://github.com/mozilla-it/sumo-infra/pull/49/files#diff-9c410465b53dcdfcf21ec5f3c459bf17
How can I do that?

See more here: https://github.com/mozilla-it/kubernetes-to-influxdb/

**Comment by The-smooth-operator** [comment]
After discussing how to reduce the number of deployments, we arrived to the next conclusion: we are going to merge the configuration from the current Telegraf deployment (the one that exposes and statsd server) into the proposed daemonset.

**Comment by The-smooth-operator** [comment]
@kfferrando @ziegeer the PR is now ready to be checked.
My intention is that deploying that we will have 2 more telegraf instances, which won't collide with each others. They should start and keep in a running state.

Few things to note:
 - I've added those to a `monitoring` namespace. This doesn't exist yet, so I added a file for it but didn't run it with the bash deployment script. Let me know what is your take in running it on a shared between environments namespace.
 - Following the current structure, we will have to deploy 2 daemonsets, one per environment. This is IMHO not acceptable, the solution I propose is to add 2 inputs to the daemonset, one with tags for prod, and with tags for stage. Each one listening in a different port. This possible solution is not reflected in the current code. Let me know if you want that I implement it.
 - For this to run, we will need a new secret possibly in the monitoring namespace. The contents of the secret should be the same than the ones in the current secret, but with different key names. How is the process of submitting this to the secrets repo? Should I go with a normal PR?

**Comment by kfferrando** [comment]
>     * I've added those to a `monitoring` namespace. This doesn't exist yet, so I added a file for it but didn't run it with the bash deployment script. Let me know what is your take in running it on a shared between environments namespace.

I think this is fine, I'll let @ziegeer weigh in on that also.

>     * Following the current structure, we will have to deploy 2 daemonsets, one per environment. This is IMHO not acceptable, the solution I propose is to add 2 inputs to the daemonset, one with tags for prod, and with tags for stage. Each one listening in a different port. This possible solution is not reflected in the current code. Let me know if you want that I implement it.

I'm good with this approach, make it so!

>     * For this to run, we will need a new secret possibly in the monitoring namespace. The contents of the secret should be the same than the ones in the current secret, but with different key names. How is the process of submitting this to the secrets repo? Should I go with a normal PR?

Yeah, why not do a PR and maybe just clarify the key names you're adding in the PR? Obviously the diff will be useless as that repo is encrypted.

Thanks @The-smooth-operator!

**Comment by The-smooth-operator** [comment]
Alright, I've pushed the change for having 2 listener for StatsD input in the same Daemonset instance. The "prod" and "stage" labels are overwritten by input. Prod listens on UDP:8125 and stage on UDP:8126.
Also reflected the change in the documentation.

**Comment by The-smooth-operator** [comment]
Thanks @ziegeer @kfferrando for your review and approval.

I've decided to first start sending kubernetes metrics (only telegraf-standalone), and later go with container_level and merge your telegraf config with the daemonset.
This is because I have to control the amount of metrics sent to influxdb, so to not overload it with series.

For this, unfortunately I'm going to close this PR and open one only with telegraf-standalone. Once we are sure that the influxdb server can support it, we will progress with container level metrics in other PR.

**Pull request closed without merging**
